export const PANABO_BARANGAYS = [
  "A.O. Floirendo",
  "Buenavista",
  "Cagaycay",
  "Cagangohan",
  "Datu Abdul Dadia",
  "Gredu (Poblacion)",
  "J.P. Laurel (Poblacion)",
  "Kasilak",
  "Katipunan",
  "Katualan",
  "Kauswagan",
  "Kiotoy",
  "Little Panay (Poblacion)",
  "Lower Panaga (Roxas)",
  "Mabunao",
  "Malativas",
  "Manay",
  "Nanyo",
  "New Malaga (Dalisay)",
  "New Malitbog",
  "New Pandan (Poblacion)",
  "New Visayas",
  "Quezon",
  "Salvacion",
  "San Francisco (Poblacion)",
  "San Nicolas (Poblacion)",
  "San Roque",
  "San Vicente",
  "Santa Cruz",
  "Santo Niño (Poblacion)",
  "Southern Davao",
  "Tagpore",
  "Tibungol",
  "Upper Licanan",
  "Waterfall",
] as const;

export type Barangay = (typeof PANABO_BARANGAYS)[number];

export const BARANGAY_OPTIONS = PANABO_BARANGAYS.map((barangay) => ({
  value: barangay,
  label: barangay,
}));
